added some project ideas
praveenscience/Hacktoberfest-Project-Ideas pull request #127
Opened 2021-09-24 17:26 UTC by aman34503

2021-09-25 03:52 UTC, aman34503 commented
When will this Request get merged

2021-09-27 04:25 UTC, vikasbhalla05 commented
I'm thinking the same thing
@aman34503

2021-09-27 17:12 UTC, praveenscience commented
@vikasbhalla05 Yours has been merged.
@aman34503 I have a full time job, and there are 20+ PRs now to review. I am doing it one by one. Doing it once per week. Hope that clarifies your question.

2021-09-27 17:13 UTC, praveenscience requested changes
Few changes. Sorry.

2021-09-27 17:40 UTC, aman34503 commented
> @vikasbhalla05 Yours has been merged.
> @aman34503 I have a full time job, and there are 20+ PRs now to review. I am doing it one by one. Doing it once per week. Hope that clarifies your question.

Sorry, i didn't mean this, i am only asking.

2021-09-27 17:40 UTC, aman34503 commented on README.md
> +  * URL shortener
done.

2021-10-01 19:23 UTC, praveenscience commented
@aman34503 Yes I know. Don't worry, didn't take it in the wrong sense man. 😁

2021-10-01 19:24 UTC, praveenscience approved these changes
👍

2021-10-01 19:24 UTC, merged

2021-10-01 19:24 UTC, praveenscience commented
@aman34503 Thanks for your contribution. Optional Request: [Subscribe to my **YouTube Channel**](https://www.youtube.com/praveenscience?sub_confirmation=1), if you haven't already subscribed and share it with your friends too.