added movie ticket booking website in html & css
praveenscience/Hacktoberfest-Project-Ideas pull request #36
Opened 2020-10-03 19:56 UTC by Jaishree18

2020-10-03 20:03 UTC, praveenscience requested changes
Can you check this please? It should be under full stack.

2020-10-03 20:03 UTC, praveenscience commented on README.md
> +* Movie Ticket Booking System
Won't this come in Full Stack?

2020-10-03 20:21 UTC, Jaishree18 commented
I have tried changing, can you please review again

On Sun, 4 Oct, 2020, 1:34 am Praveen Kumar, <notifications@github.com>
wrote:

> *@praveenscience* requested changes on this pull request.
>
> Can you check this please? It should be under full stack.
> ------------------------------
>
> In README.md
> <https://github.com/praveenscience/Hacktoberfest-Project-Ideas/pull/36#discussion_r499177703>
> :
>
> > @@ -19,6 +19,7 @@ We'll organise into different streams here. One kind request for motivation: Ple
>  * Comic Reading Site
>  * Product Landing Page
>  * Fashion E-Commerce Website
> +* Movie Ticket Booking System
>
> Won't this come in Full Stack?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/praveenscience/Hacktoberfest-Project-Ideas/pull/36#pullrequestreview-501570888>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOVEBOF56S4GXK5OR446U4DSI57TLANCNFSM4SDG44YQ>
> .
>

2020-10-16 19:38 UTC, praveenscience approved these changes
👍

2020-10-16 19:38 UTC, merged

2020-10-16 19:38 UTC, praveenscience commented
Thanks for your contribution. Optional Request: [Subscribe to my **YouTube Channel**](https://www.youtube.com/praveenscience?sub_confirmation=1), if you haven't already subscribed and share it with your friends too.