Update README.md
praveenscience/Hacktoberfest-Project-Ideas pull request #70
Opened 2020-10-17 15:00 UTC by santhu342

Update php development

2020-10-17 15:01 UTC, santhu342 commented
Php development app update

2020-10-20 09:57 UTC, praveenscience requested changes
Is it same or different?

2020-10-20 09:57 UTC, praveenscience commented on README.md
> +### PHP Development
Similar to this?
https://github.com/praveenscience/Hacktoberfest-Project-Ideas/pull/75/files

2020-10-23 07:15 UTC, praveenscience commented
Closing this as invalid.

2020-10-23 07:15 UTC, closed without merging